### ISSUE TITLE
jenkins and openjdk7

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/elife-alfred-formula#3]
does Alfred need this state? 

https://github.com/elifesciences/elife-alfred-formula/blob/master/salt/elife-alfred/init.sls#L370-L373

it has oracle java 8 available to it

**Comment by lsh-0** [comment]
https://github.com/elifesciences/elife-alfred-formula/pull/4

haven't tested it remotely just yet, but it should be done today.

**Comment by giorgiosironi** [comment]
Approved PR
